# Generated by Django 6.0.1 on 2026-02-01 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefa',
            new_name='Task',
        ),
    ]
