services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app # Reflete na pasta /app do container
      - /app/node_modules # Permanece a pasta node_modules do container