# Generated by Django 6.0.1 on 2026-02-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_etiqueta_tarefa_etiquetas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'permissions': [('can_view_all_tarefa', 'Can view tasks from all users')]},
        ),
    ]
