services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: banco
    restart: always
    ports:
      - 4000:5432
    volumes:
      - banco-data:/var/lib/postgresql/data

volumes:
  banco-data: